/**
 * Client code demonstrating the usage of generated classes from the Car domain model.
 * These classes were generated by the draw.io-to-Java code generator.
 */
public class Main {

    public static void main(String[] args) {
        // Create a Person (superclass)
        Person person = new Person();

        // Create a Driver (extends Person)
        Driver driver = new Driver();

        // Create a Car
        Car car = new Car();

        // Set up the association: Driver drives (1) Car
        driver.setCar(car);

        // Create Wheels and add them to the Car (has N relationship)
        Wheel frontLeft = new Wheel();
        Wheel frontRight = new Wheel();
        Wheel rearLeft = new Wheel();
        Wheel rearRight = new Wheel();

        car.addWheel(frontLeft);
        car.addWheel(frontRight);
        car.addWheel(rearLeft);
        car.addWheel(rearRight);

        // Create a Licence Plate and associate it with the Car (has 1 relationship)
        LicencePlate plate = new LicencePlate();
        car.setLicencePlate(plate);

        // Demonstrate accessing the generated relationships
        System.out.println("Driver's car: " + driver.getCar());
        System.out.println("Number of wheels: " + car.getWheels().size());
        System.out.println("Licence plate: " + car.getLicencePlate());
        System.out.println("Driver is a Person: " + (driver instanceof Person));
    }
}
