/**
 * Client code demonstrating the usage of generated classes from the University domain model.
 * These classes were generated by the draw.io-to-Java code generator.
 */
public class Main {

    public static void main(String[] args) {
        // Create a University
        University mcmaster = new University();

        // Create Departments
        Department engineering = new Department();
        Department science = new Department();
        mcmaster.addDepartment(engineering);
        mcmaster.addDepartment(science);

        // Create Buildings and Rooms
        Building jhe = new Building();
        Room room101 = new Room();
        Room room202 = new Room();
        jhe.addRoom(room101);
        jhe.addRoom(room202);
        mcmaster.addBuilding(jhe);

        // Create Professors (extends Person)
        Professor profDavid = new Professor();
        engineering.addProfessor(profDavid);

        // Create Courses with Assignments and Textbooks
        Course softwareDesign = new Course();
        Assignment assignment1 = new Assignment();
        Assignment assignment2 = new Assignment();
        softwareDesign.addAssignment(assignment1);
        softwareDesign.addAssignment(assignment2);

        Textbook designPatterns = new Textbook();
        softwareDesign.setTextbook(designPatterns);

        // Department offers courses
        engineering.addCourse(softwareDesign);

        // Professor teaches courses
        profDavid.addCourse(softwareDesign);

        // Create Students (extends Person)
        Student student1 = new Student();
        Student student2 = new Student();

        // Students enroll in courses
        student1.addCourse(softwareDesign);
        student2.addCourse(softwareDesign);

        // Students receive grades
        Grade gradeA = new Grade();
        Grade gradeB = new Grade();
        student1.addGrade(gradeA);
        student2.addGrade(gradeB);

        // Demonstrate accessing the generated relationships
        System.out.println("University departments: " + mcmaster.getDepartments().size());
        System.out.println("University buildings: " + mcmaster.getBuildings().size());
        System.out.println("Engineering courses: " + engineering.getCourses().size());
        System.out.println("Engineering professors: " + engineering.getProfessors().size());
        System.out.println("Software Design assignments: " + softwareDesign.getAssignments().size());
        System.out.println("Software Design textbook: " + softwareDesign.getTextbook());
        System.out.println("Professor teaches courses: " + profDavid.getCourses().size());
        System.out.println("Student 1 courses: " + student1.getCourses().size());
        System.out.println("Student 1 grades: " + student1.getGrades().size());
        System.out.println("Rooms in building: " + jhe.getRooms().size());
        System.out.println("Student is a Person: " + (student1 instanceof Person));
        System.out.println("Professor is a Person: " + (profDavid instanceof Person));
    }
}
